# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.16.0
_src_path: gh:radio-aktywne/template-app-litestar
accountname: radio-aktywne
appname: emipass
description: WebRTC to SRT passthrough 💨
docs: true
docsurl: https://radio-aktywne.github.io/app-emipass
email: it@radioaktywne.pl
envprefix: EMIPASS
events: false
imagename: apps/emipass
importname: emipass
port: 11000
registry: true
releases: true
reponame: app-emipass
repourl: https://github.com/radio-aktywne/app-emipass
