# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast streaming passthrough 🎤
docs: true
docsurl: https://radio-aktywne.github.io/loris
email: it@radioaktywne.pl
envprefix: LORIS
events: false
imagename: services/loris
importname: loris
port: 11000
registry: true
releases: true
reponame: loris
repourl: https://github.com/radio-aktywne/loris
servicename: loris
