# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast streaming passthrough 🎤
docs: true
docsurl: https://radio-aktywne.github.io/emipass
email: it@radioaktywne.pl
envprefix: EMIPASS
events: false
imagename: services/emipass
importname: emipass
port: 11000
registry: true
releases: true
reponame: emipass
repourl: https://github.com/radio-aktywne/emipass
servicename: emipass
