services:
  emipass:
    build:
      context: ./
      network: host
    environment:
      - "EMIPASS__SERVER__HOST=${EMIPASS__SERVER__HOST:-0.0.0.0}"
      - "EMIPASS__SERVER__PORTS__HTTP=${EMIPASS__SERVER__PORTS__HTTP:-11000}"
      - "EMIPASS__SERVER__PORTS__WHIP=${EMIPASS__SERVER__PORTS__WHIP:-11001}"
      - "EMIPASS__SERVER__PORTS__RTP__MIN=${EMIPASS__SERVER__PORTS__RTP__MIN:-11002}"
      - "EMIPASS__SERVER__PORTS__RTP__MAX=${EMIPASS__SERVER__PORTS__RTP__MAX:-11002}"
      - "EMIPASS__STREAMER__STUN__HOST=${EMIPASS__STREAMER__STUN__HOST:-stun.l.google.com}"
      - "EMIPASS__STREAMER__STUN__PORT=${EMIPASS__STREAMER__STUN__PORT:-19302}"
      - "EMIPASS__STREAMER__TIMEOUT=${EMIPASS__STREAMER__TIMEOUT:-PT1M}"
    network_mode: host
