services:
  loris:
    build:
      context: ./
      network: host
    environment:
      - "LORIS__SERVER__HOST=${LORIS__SERVER__HOST:-0.0.0.0}"
      - "LORIS__SERVER__PORTS__HTTP=${LORIS__SERVER__PORTS__HTTP:-11000}"
      - "LORIS__SERVER__PORTS__WHIP=${LORIS__SERVER__PORTS__WHIP:-11001}"
      - "LORIS__SERVER__PORTS__RTP__MIN=${LORIS__SERVER__PORTS__RTP__MIN:-11002}"
      - "LORIS__SERVER__PORTS__RTP__MAX=${LORIS__SERVER__PORTS__RTP__MAX:-11002}"
      - "LORIS__SERVER__TRUSTED=${LORIS__SERVER__TRUSTED:-*}"
      - "LORIS__STREAMER__STUN__HOST=${LORIS__STREAMER__STUN__HOST:-stun.l.google.com}"
      - "LORIS__STREAMER__STUN__PORT=${LORIS__STREAMER__STUN__PORT:-19302}"
      - "LORIS__STREAMER__TIMEOUT=${LORIS__STREAMER__TIMEOUT:-PT1M}"
      - "LORIS__DEBUG=${LORIS__DEBUG:-false}"
    network_mode: host
